### ISSUE TITLE
[1.19.2] Access Widener Error on startup

### ISSUE THREAD

**Issue by Hahahavana** [Talia-12/Hexal#10]
[latest.log](https://github.com/Talia-12/Hexal/files/10102598/latest.log)

**Comment by Hahahavana** [comment]
On a sidenote I have genuinely no idea why this error is happening, as I have a fairly similar setup on a seperate machine where it works fine.

**Comment by Talia-12** [comment]
well, I also have no idea what's causing this; can you try removing all the mods not required by hexal to see if it's an incompatibility somehow, and if yes try and find what it's incompatible with? also, in future you should use something like [pastebin](pastebin.com) to upload your log so I don't have to download the log to look at it

**Comment by Hahahavana** [comment]
Ok, I checked the setup where Hexal DOES work and it looks like the error is specific to the 2.4 fabric version. I made a fresh instance, with only Hexal and Dependencies and got the same access widener error on startup. Its the exact same error codes as the previous log, so It's specifically an issue with Hexal 2.4 rather than any incompatibilities.

**Comment by Hahahavana** [comment]
2.3 works fine, in comparison.

**Comment by Talia-12** [comment]
Alright, I think I figured out what caused it, setup the uploading to modrinth using the wrong jar task for fabric. Could you try with the versions I just released to see if that fixed it?

**Comment by Hahahavana** [comment]
> Alright, I think I figured out what caused it, setup the uploading to modrinth using the wrong jar task for fabric. Could you try with the versions I just released to see if that fixed it?

Did a test with both Hexal 2.5 and MI 0.2, game loaded without crashing, loading into a world worked out fine, and Hex Casting registers as having mods installed. Looks like whatever you did fixed the issues! Cheers.

**Comment by Talia-12** [comment]
cool, thanks for testing it!
