### ISSUE TITLE
A weird issue with break block spell on mote nexus

### ISSUE THREAD

**Issue by maraxin** [Talia-12/Hexal#100]
![2023-07-09_21 58 01](https://github.com/Talia-12/Hexal/assets/53759232/88176e00-4668-44ec-8659-ff074c479a67)
If you use break block on mote nexus, it'll actually break and drop its contents, but the ghost block will be still here (until you right click on it or something like that)
Here is log
![изображение](https://github.com/Talia-12/Hexal/assets/53759232/5804ed26-e8b4-4166-83e7-5f13aba3e648)

**Comment by Talia-12** [comment]
fixed for the next release!
