### ISSUE TITLE
Use Item Duplication With Supplementaries Cage

### ISSUE THREAD

**Issue by JohnDog3112** [Talia-12/Hexal#102]
When you use the use item spell with a supplementeries cage, it releases the mob, but the mote doesn't change. In addition, it seems to void whatever is in your main hand when you cast it. You can see this happening here: [https://youtu.be/l2Ehe-y0aAs](https://youtu.be/l2Ehe-y0aAs).

**Comment by Talia-12** [comment]
figured out what supplementeries is doing weird, should be fixed in the next version
