### ISSUE TITLE
[Bug] Saving a wisp with a schematic from Create will crash

### ISSUE THREAD

**Issue by Buggy123** [Talia-12/Hexal#105]
Mainly the title. If a wisp is encompassed by the area of a schematic and quill from Create and you attempt to save the schematic while the wisp exists, it crashes. Occurs even with really simple wisp contentts like just a bunch of Delay Wisp.

Create version is 5.0, Hexal version is... whichever one came before the different types of gates. I'm pretty sure this isn't going to be hard to reproduce though.

**Comment by Talia-12** [comment]
it would be helpful if you could provide an example of the log resulting from a crash (ideally uploaded to a site like pastebin so I don't have to download it onto my computer).

**Comment by Buggy123** [comment]
https://pastebin.com/0ryJyhcL

**Comment by Talia-12** [comment]
should be fixed for the next release now
