### ISSUE TITLE
Bound Wisps are very broken

### ISSUE THREAD

**Issue by Robotgiggle** [Talia-12/Hexal#107]
Based on some testing done on the Hexxycraft server:
- Bound wisps only cast their stored spell once
- If there's still media left after this cast, the wisp just sits there doing nothing
- If it runs out of media partway through the cast, it **[crashes the server](https://mclo.gs/mgsqYiA)**

Attempting to consume a bound wisp also acts strangely:
- When I load the Consume Wisp spell from a scroll and attempt to hermes it, hermes turns grey and hangs
- Exiting and reopening the casting grid makes the grey hermes vanish
- Casting hermes a second time successfully consumes the wisp, but it triggers the increased cost for consuming a wisp owned by another player (and yes, I checked, I do still own the wisp)

**Comment by Talia-12** [comment]
fixed for the next version, didn't experience the consume wisp throwing exceptions occasionally issue so it may be fixed by the fixes to the wisps, or it may pop up again, make a new issue if it does
