### ISSUE TITLE
Incorrect cost for Consume Wisp

### ISSUE THREAD

**Issue by brianide** [Talia-12/Hexal#111]
The book says of Consume Wisp:

`Costs either an Amethyst Shard if the wisp is owned by you or has allowed transfer with the caster or caster's owner, or half again as much media as the consumed wisp contains if the wisp is owned by another and has now allowed it.`

However, when I cast it on a wisp I own, it seems to consume (with default configs) 1.5x the amount of media in the wisp, as if I didn't own it.

I took at look at the source and I think the cause might be that the `fightConsume` method in [BaseCastingWisp](https://github.com/Talia-12/Hexal/blob/e6f741c8b9c16142e17bccdd1fb68740af611185/Common/src/main/java/ram/talia/hexal/common/entities/BaseCastingWisp.kt#L78) has its logic backwards; ie. it looks like it returns `true` when both wisps have the same caster.

**Comment by Talia-12** [comment]
This shouldd be fixed in the latest release, please make a new issue if I failed to correctly do that
