### ISSUE TITLE
Patchouli pages for Types are broken on Fabric 0.2.6

### ISSUE THREAD

**Issue by Ryminer2** [Talia-12/Hexal#12]
![image](https://user-images.githubusercontent.com/6020841/205201036-8f9b2517-5da3-4830-9b21-586f68cc1b4a.png)
![image](https://user-images.githubusercontent.com/6020841/205201064-e021b7ad-1cb5-4667-a0b0-05a2099f3b01.png)

**Comment by RedstoneParadox** [comment]
Looks like the last one should be `hexal.page.types.type/iota`

**Comment by Talia-12** [comment]
Fixed in the beta release, will be fixed for the next release.
