### ISSUE TITLE
Feature suggestion: backport of writeable in-world foci

### ISSUE THREAD

**Issue by anna-s-h** [Talia-12/Hexal#17]
I understand completely if this is an unreasonable request but I'd love it if you would be willing to add that feature from 1.19 Hex to 1.18 Hexal.

**Comment by Talia-12** [comment]
I would definitely look into doing that if I was updating 1.18, but I've unfortunately stopped updating Hexal 1.18 for the same reason that Hex Casting has stopped updating 1.18 (supporting two versions is much more work).
