### ISSUE TITLE
Cyclic wisps spam the log

### ISSUE THREAD

**Issue by object-Object** [Talia-12/Hexal#21]
This message is constantly sent in the log file when a cyclic wisp is active:
```
[00:05:40] [Server thread/INFO]: scheduling casting sound, level is ServerLevel[New World]
[00:05:40] [Render thread/INFO]: playing casting sound, level is ClientLevel
```

**Comment by Talia-12** [comment]
Reckon it's better to change the debug level to debug/trace, or just get rid of them? For now I'm commenting them out since I'm not sure whether the log file would include them even at lower debug levels, but I might add them back at debug level if that would also fix the issue.

**Comment by Talia-12** [comment]
pretty sure I've fixed this, make a new issue if it's still a problem.
