### ISSUE TITLE
Crash on Player Join for Forge Server

### ISSUE THREAD

**Issue by DeathExDorumon** [Talia-12/Hexal#26]
Just tested this on a server with only Hexal and Hexcasting, with dependencies.
Forge version is latest for 1.19.2, that being Forge 43.2.4

Worth noting that it seems to have no issue when doing a singleplayer world, from what I noticed in a quick test.
If anything else is needed I am happy to help.
Also, only server crashes, player is simply disconnected.

[crash-2023-02-17_20.29.44-server.txt](https://github.com/Talia-12/Hexal/files/10772881/crash-2023-02-17_20.29.44-server.txt)
[debug.log](https://github.com/Talia-12/Hexal/files/10772884/debug.log)
[latest.log](https://github.com/Talia-12/Hexal/files/10772885/latest.log)
[Clients debug.log](https://github.com/Talia-12/Hexal/files/10772886/Clients.debug.log)

**Comment by Talia-12** [comment]
Pretty sure this is fixed in the latest release; if not, please make a new issue (if you make a new issue please add links to the logs after uploading them to pastebin or similar, just uploading them to github attached to the issue means I need to download them to read them which is a chore)
