### ISSUE TITLE
Issue when hosting a forge server

### ISSUE THREAD

**Issue by FinSilver-gist** [Talia-12/Hexal#3]
Server crashed on startup      
  Failure message: Hexal (hexal) has failed to load correctly
                java.lang.reflect.InvocationTargetException: null
        Mod Version: 0.1.4
        Mod Issue URL: https://github.com/Talia-12/Hexal/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER
Full report below:
[crash-2022-09-27_12.53.31-fml.txt](https://github.com/Talia-12/Hexal/files/9658582/crash-2022-09-27_12.53.31-fml.txt)

**Comment by Talia-12** [comment]
Alright, this *should* be fixed in [v0.1.5](https://github.com/Talia-12/Hexal/releases/tag/0.1.5), thanks for sending the bug report
