### ISSUE TITLE
There is no way to make the Mote Nexus

### ISSUE THREAD

**Issue by Hate9** [Talia-12/Hexal#37]
Also the Mote Nexus looks wrong and breaks in one hit. I assume this is because it's unfinished, but I can't imagine giving it a break difficulty and crafting recipe is that hard.

**Comment by GuiTaek** [comment]
Hi, there is a recipe but it is broken. In https://github.com/Talia-12/Hexal/blob/fc4ec6dd64660c0d2b1f27eaebb9a756de2afa62/Common/src/main/java/ram/talia/hexal/datagen/recipes/HexalplatRecipes.kt in line 42, the class "VillagerIngredient" is not correctly used. According to https://github.com/gamma-delta/HexMod/blob/f42a088c3449215478b430bbf1c4ad875fcff493/Common/src/main/java/at/petrak/hexcasting/datagen/recipe/HexplatRecipes.java 409 following this is used in another way. Indeed, looking with jei into the flay mind recipe, shows a broken villager (without translation) whereas the other flay mind recipes are with correct translations.

**Comment by Talia-12** [comment]
Thanks for the report, these have both been fixed for the next release!
