### ISSUE TITLE
Hexal and Create are seemingly incompatible

### ISSUE THREAD

**Issue by RealArcanePhysics** [Talia-12/Hexal#4]
Hi, I just wanted to let you know that a personal build from this repo(1.16-5, built from commit "3abc1cb") is seemingly incompatible with Create(0.5.0e).

**Error message:** "Create(create) has failed to load correctly", "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered"

**Crash report:** https://mclo.gs/qpNUq9o

**Mods:** Create(0.5.0e), Flywheel(0.6.5), Hex Casting(0.9.4), Hexal(0.16-5), Kotlin for Forge(3.7.1), Patchouli(1.18.2-71.1), PAUCAL(0.4.7)

**Mod loader:** Forge(40.1.84)

[crash-2022-10-16_20.10.05-fml.txt](https://github.com/Talia-12/Hexal/files/9796192/crash-2022-10-16_20.10.05-fml.txt)

**Comment by Talia-12** [comment]
Well that's pretty annoying, thanks for the bug report. Probably not gonna be able to fix this for a couple weeks so I guess I'm not releasing a new version of Hexal anytime soon.

**Comment by Talia-12** [comment]
Alright I've finally gotten around to testing this, and it seems like putting Create and Flywheel directly into the mods environment in the dev environment breaks everything, but when I built Hexal into a jar and then created a new instance with all the mods listed everything worked fine?
