### ISSUE TITLE
[1.19.2] - Hexal Incompatibility with Integrated Dynamics

### ISSUE THREAD

**Issue by ToxinZangoose** [Talia-12/Hexal#40]
Hello,

This is Intego from the Hex Casting Discord, I wanted to report a bug with Integrated Dynamics, CyclopsCore, and Common Capabilities.

Here is the crashlog and how to reproduce the bug.

1. Boot Minecraft 1.19.2
2. Go to create world
3. Notice the bug and crash to desktop.

[crash-2023-03-29_17.38.54-server.txt](https://github.com/Talia-12/Hexal/files/11106701/crash-2023-03-29_17.38.54-server.txt)

**Comment by PokeMaserJ** [comment]
What versions of the mods though?

**Comment by PokeMaserJ** [comment]
Looks like 0.2.13 fixes this. Since I was able to load a world with both mods.
