### ISSUE TITLE
Wisps do not seem to despawn

### ISSUE THREAD

**Issue by AsiPanda** [Talia-12/Hexal#41]
Hi,

I am not exactly sure what the cause of this issue is, but I could not start my server today. After extensive profiling and debugging, I found out that there were over 53,000 wandering wisps spawned, taking the entirety of the server thread.

I have fixed this by killing all the "hexal:wisp/wandering" entities prior to anyone joining, which has fixed the problem for now.

**Comment by Talia-12** [comment]
alright, should be fixed for the next version!
