### ISSUE TITLE
Craft spell does not accept single iotas, despite the book indicating that it should

### ISSUE THREAD

**Issue by beholderface** [Talia-12/Hexal#42]
![2023-04-04_23 40 59](https://user-images.githubusercontent.com/13290805/229975669-e2efd8fe-683a-4f38-84db-103d9adaefd7.png)
![2023-04-04_23 42 05](https://user-images.githubusercontent.com/13290805/229975699-e01dce9e-e0da-4c24-81b0-3863d5db9234.png)

**Comment by Talia-12** [comment]
I think this has been fixed for a while and I forgot to close it, but it's definitely fixed now.
