### ISSUE TITLE
[Suggestion] Interaction pattern

### ISSUE THREAD

**Issue by miyucomics** [Talia-12/Hexal#44]
There could be a pattern that takes in two vectors and a mote: a position, a direction, and an item. Then it would right-click with that item with the position and direction as if a player had done it, similar to Create deployers. Potentially there could be a second pattern designed specifically for targeting entities. The cost of the pattern could be dependent on distance.

Some uses could be:
- applying wax to copper with hexcasting
- milking cows with hexcasting
- starting fires with flint and steel or fire charges

**Comment by object-Object** [comment]
As mentioned on Discord, I think it's important that this only allow right click interactions, or at least not allow dealing damage, so that it doesn't effectively become an instant damage spell

**Comment by walksanatora** [comment]
i plan on implementing this in hextweaks (but talia may beat me to it)
(Vec|Entity,Mote -> )

**Comment by Talia-12** [comment]
This was implemented by computerwhisperer for 0.2.16!
