### ISSUE TITLE
[Suggestion] Nerf gates, sort of

### ISSUE THREAD

**Issue by object-Object** [Talia-12/Hexal#46]
Reposting/aggregating from Discord so it's not buried forever.

Right now, there are very few uses for GTP that gates can't do for a fraction of the price. GTP probably needs a buff, yes, but in the meantime I (and others) think gates should probably be made a bit less awesome. We have two suggestions for this:
* Require a position to be given when creating the gate iota, not when teleporting entities using it. This prevents gates from being a strictly better GTP, while still allowing permanent teleportation networks, item collectors for stationary builds, and such.
* Add another type of gate iota, similar to a true name, that always teleports to wherever the creator is. It should probably have the same protections against writing as a true name does. This allows many of the cool utility-style hexes to still work (eg. remote railguns, item retrieval, wireless charging), but only if the destination is a player, generally the one casting the hex.

**Comment by Talia-12** [comment]
come up with a solution to this that I'm happy with
- Changed Gates to now have 3 types:
  - Location Anchored, which will always teleport the marked entities to the same location every time that gate is closed.
  - Entity Anchored, which will teleport the marked entities to the location of the anchor entity (plus an offset defined when the gate is created)
  - Drifting, which has the same behaviour as current gates, with an additional cost per distance gated per entity.
