### ISSUE TITLE
[1.19.2-fabric] The slipway keep summoning wisps infinitely

### ISSUE THREAD

**Issue by vakus** [Talia-12/Hexal#47]
Me and few of my friends have been playing own modpack with this mod, and we noticed a huge amount of entities which were killing the server, every now and then we ran `/kill @e[type=!player]` command and we were getting around 53 thousands entities killed. We sometimes ran into chunks which would just straight out crash out server.

Today I have investigated the cause of this and found that underneath one of the players base there was a slipway, which kept summoning wisps, which have not been emulated themselves, which as result would never die. As a side effect when my friend was logging in onto the server, the server would out right shutdown.

I have initially tracked down which chunk was causing the crashing, and then have investigated which exact position was causing the crashes by progressively narrowing down `/kill @e[x=2096,dx=16,z=560,dz=16,y=-64,y=255]` command until I have found that at x2109 y28-30, z576 there was 53 thousands entities. I found out what the entity was by using `/say @e[x=2109,z=576,y=28,dy=4]` which has returned a big chunk of text just saying `wandering wisp`.

![image](https://user-images.githubusercontent.com/8487993/231758057-f7173126-eb31-4b98-9233-9cd0b025c941.png)

We have been able to temporarily restore the world to usable state by running `/kill @e[type=hexal:wisp/wandering]` however this appears to be recurring issue.
![image](https://user-images.githubusercontent.com/8487993/231759705-54142a05-77ac-4e57-957d-439f6f44bddc.png)

since I had a singleplayer copy I have reduced chunk simulation to as low as possible, which was 5 and found that if I was 5 chunks away from the slipway, it was still summoning wisps, however those would never die.

I had a small look at the code, and looks like this potentially would cause infinite spawning of wisps.
https://github.com/Talia-12/Hexal/blob/5be3897ae3fe0d2088b5d1e127f68cfd5e13cdb5/Common/src/main/java/ram/talia/hexal/common/blocks/entity/BlockEntitySlipway.kt#L47-L57

My suggestion would be to add a check of how many wisps are already around the Slipway, and don't allow spawning more wisps if at the threshold.

<details>
<summary>screenshot of trying to say all entities within the location provided, warning fairly big photo</summary>

![image](https://user-images.githubusercontent.com/8487993/231758941-c8835419-92ed-45ec-8f29-f1d5d4c9bea5.png)

</details>

**Comment by Talia-12** [comment]
Should be fixed now, stop spawning if there's more than 20 wisps within 32 blocks of the slipway.

**Comment by Talia-12** [comment]
also, thank you for the very detailed issue report!

**Comment by vakus** [comment]
no worries, I was trying to provide enough information to resolve this, I seen plenty of bug reports before where it was hard to tell what is causing the issues and as result they could not be resolved. Thanks for the quick fix and update, hopefully this will resolve the issue for us. Thanks again
