### ISSUE TITLE
Crash as soon as I try to use phase block spell

### ISSUE THREAD

**Issue by maraxin** [Talia-12/Hexal#51]
So I tried to use phase block for 10 seconds on a grass block, it crashed as soon as I tried to use it
[crash-2023-04-18_13.33.53-server.txt](https://github.com/Talia-12/Hexal/files/11260752/crash-2023-04-18_13.33.53-server.txt)

**Comment by Talia-12** [comment]
fixed for the next release, but till then you can fix it by including the [lib39](https://modrinth.com/mod/lib39/versions) mod
