### ISSUE TITLE
Crossing through the nether portal causes all loaded cyclic wisps owned by that player to lock up

### ISSUE THREAD

**Issue by computer-whisperer** [Talia-12/Hexal#53]
Traveling to any different dimension causes all loaded cyclic wisps owned by that player to lock up. Returning to the original dimension does not cause wisps to continue operations, instead they are entirely static until the whole server is reloaded.

Putting wisps into unloaded chunks before crossing seems to stop this from happening, though it is an inconvenient workaround.

Ideally they would continue functioning while the player is in the other dimension, but at least they should be able to continue operation once the player returns.

Tested and reproduced explicitly with the Nether and a dimension from Mine Cells.

Tested exclusively on a private server, I have not tested this in single-player mode.

Seen with the modpack "All of Fabric 6" versions 1.5.2 and 1.5.4.
Minecraft 1.19.2,
Hex Casting 0.10.3
Hexal 0.2.14, 
Fabric API v0.76.0+1.19.2

**Comment by Talia-12** [comment]
Fixed! Wisp.scheduledCast wasn't getting set back to false if the wisp's cast got cancelled when the caster was in a different dimension.
