### ISSUE TITLE
A cyclic wisp spawning 2 other cyclic wisps in the same tick falsely triggers a recursion-depth fault

### ISSUE THREAD

**Issue by computer-whisperer** [Talia-12/Hexal#56]
Here is a simple reproducing spell

![image](https://user-images.githubusercontent.com/3778956/234690035-14d04c9c-5ef1-4e92-937c-85afb76d9eed.png)

It took me many many hours to figure out that this was why my power distribution wisps were occasionally crashing...

Seen with the modpack "All of Fabric 6" versions 1.5.2 and 1.5.4.
Minecraft 1.19.2,
Hex Casting 0.10.3
Hexal 0.2.14,
Fabric API v0.76.0+1.19.2

**Comment by Talia-12** [comment]
this is intentional, but I should really make the error message clearer; basically, wisps can only make at most 1 new wisp each tick, to prevent fork-bomb issues.

**Comment by Talia-12** [comment]
alright, made a mishap with a clearer error message for this
