### ISSUE TITLE
Wisp bind does not clear on wisp death

### ISSUE THREAD

**Issue by computer-whisperer** [Talia-12/Hexal#57]
It appears that wisp binds are not always cleared when the bound wisp dies, instead they stay bound and do not allow other wisps to bind to that player. Disconnecting and reconnecting resets the issue.

Here are steps to reproduce:
Casting the "get bound wisp" spell shown results in:
![image](https://user-images.githubusercontent.com/3778956/234698328-b72ecbed-fcf5-46a0-9d67-f8552b093f3f.png)

Casting the "spawn bound wisp" spell shown results in:
![image](https://user-images.githubusercontent.com/3778956/234698427-46e9561c-d248-41cb-99e7-6189444e11aa.png)

Then the wisp is deleted with a "consume wisp" spell, then the "get bound wisp" spell is executed resulting in this:
![image](https://user-images.githubusercontent.com/3778956/234698584-3f3f7284-0ce9-4141-aed6-5932ec22f9c2.png)

Then the "spawn bound wisp" spell is re-executed resulting in this:
![image](https://user-images.githubusercontent.com/3778956/234698705-03b57c22-0206-4ff3-8a6d-22b347a1dc30.png)

Restarting the client causes the "get bound wisp" spell to return NULL once more.

Seen on a private server with the modpack "All of Fabric 6" versions 1.5.2 and 1.5.4.
Minecraft 1.19.2,
Hex Casting 0.10.3
Hexal 0.2.14,
Fabric API v0.76.0+1.19.2

**Comment by beholderface** [comment]
I can confirm this also happens on Forge

**Comment by Talia-12** [comment]
Alright, fixed!
