### ISSUE TITLE
[0.1.13] Links(receiving) are broken.

### ISSUE THREAD

**Issue by alexyzer** [Talia-12/Hexal#60]
I have tested this bug in the earlier 0.1.12 forge and in the latest 0.2.14 fabric version and everything works properly.
Iotas are still sent through the link, they appear in the received_iotas NBT of the wisp, but no spell regarding iota reception works.

Recitation Reflection - returns Null no matter what.
Postmaster's Reflection - returns 0.
Listen - will halt hex forever.

**Comment by Talia-12** [comment]
Will be fixed in the next 1.18.2 release which I will do soon
