### ISSUE TITLE
Gate's Reflection serial number progression resets after server restart

### ISSUE THREAD

**Issue by computer-whisperer** [Talia-12/Hexal#65]
When you call Gate's Reflection multiple times during one server run session, the serial progression appears to function as designed (Gate 0, gate 1, gate 2, etc).

Upon server restart however, the created gate indexes appear to start again at gate 0. This means that reaching new gate numbers requires wasting tons of media to re-create all existing gates first.

Seen with the modpack "All of Fabric 6" version 1.5.4.
Minecraft 1.19.2,
Hex Casting 0.10.3
Hexal 0.2.14,
Fabric API v0.76.0+1.19.2

**Comment by Talia-12** [comment]
This has been fixed for the next hexal version.

**Comment by SamsTheNerd** [comment]
this seems to still sometimes be an issue on 0.2.17/18. 

The screenshot is just me making new gates repeatedly. My game crashed (for unrelated reasons) between gates 2 and (2nd) 0, but Chloe on discord had the same result with no crashing. 
<img width="966" alt="image" src="https://github.com/Talia-12/Hexal/assets/18472542/7c966548-6f29-41d5-9856-c4981bca45cd">
I was thinking it might be a case of it happening on older worlds but this one is a fresh world on 0.2.17, and again I think chloe got it on a fresh 0.2.18 world.

I haven't seen anyone talk about it on hexxycraft though, so *maybe* it's singleplayer only or only some worlds or something? not sure though

**Comment by macks2008** [comment]
This issue might still be happening on hexxytest (which is running 0.3.0-2, at least according to the toml). There are a lot of duplicate gates. I'm going to open a new issue in any case, because SOMETHING is causing ID duplication/"gate aliasing".
