### ISSUE TITLE
Phase block still crashing even with blacklist spell

### ISSUE THREAD

**Issue by itsdinkd** [Talia-12/Hexal#67]
Still crashing and i blacklisted Phase Block... I am not adding lib39 as I don't want to add another library if I can just blacklist the spell.

https://mclo.gs/uzYxxHO

![image](https://github.com/Talia-12/Hexal/assets/35115304/037ebc24-1471-4061-8f8d-b9bf1fca0cc3)

**Comment by Talia-12** [comment]
The deny list not working is a base hex casting bug, but the spell will no longer crash the game in the next hexal version.
