### ISSUE TITLE
Wisps start malfunctioning if you have died during your current play session

### ISSUE THREAD

**Issue by beholderface** [Talia-12/Hexal#68]
Forge 43.2.6, Hexal 0,2.14
I first discovered this when testing a hex which summons a wisp which repeatedly summons wisps that trigger the instant death gemini mishap. The mishap worked once, after which point I stopped dying from it (it was still treated as a mishap, the wisps still died). It worked one more time after closing and reopening the world. I wasn't going to make an issue about this, since it seemed harmless enough.

Then I happened to try out another wisp-using hex ([cart propeller 2.txt](https://github.com/Talia-12/Hexal/files/11522933/cart.propeller.2.txt)) and it starting consistently mishapping just a few ticks after casting, when I hadn't done anything to the pattern list since yesterday, when it was working fine. It looked like the wisp was rushing off to somewhere that was definitely not my feet position, which is what it should have been going to. in I did some experimentation, initially assuming it to be related to the issue with wisps and the gemini mishap, but then found that dying to simple fall damage triggered it as well.

Just now, I did some more testing, and it seems that at least part of the malfunction is that the wisps thought I was still at my spawnpoint, determined by summoning a wisp with the pattern list `mind's reflection, compass' purification II, reveal`. Staff casting the same thing does not seem to have this issue.

I have not tested this with leaving and rejoining servers.

**Comment by beholderface** [comment]
Additionally, Nurse's Purification returns 0 when executed by wisps after respawning, so I guess the wisp thinks I'm dead?

**Comment by Talia-12** [comment]
ah, I should probably check whether the player entity I'm storing is dead, shouldn't I

**Comment by Talia-12** [comment]
never mind, I'm already doing that properly, apparently this will need more testing

**Comment by Talia-12** [comment]
Alright, fixed, turns out the wisps were handling it fine and it was the WispCastingManager that was erroneously holding a reference to the deleted player
