### ISSUE TITLE
Invalid player data when trying to create a new world

### ISSUE THREAD

**Issue by Sunconure11** [Talia-12/Hexal#74]
https://gist.github.com/Sunconure11/9fff1ced4518111c688f9eacf9466854

**Comment by Shibva** [comment]
https://gist.github.com/Shibva/f074344afc839544503962a581f44769

**Comment by kristifristi** [comment]
[https://pastebin.com/ckMnKrtV](https://pastebin.com/ckMnKrtV)

**Comment by nvb-uy** [comment]
Having the same issue with Hexal 0.2.15

**Comment by XieDeWu** [comment]
Same thing over here

**Comment by Sunconure11** [comment]
@Talia-12

**Comment by Talia-12** [comment]
Fixed in the latest release
