### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by ElNico56** [Talia-12/Hexal#8]
![image](https://user-images.githubusercontent.com/18220871/203292997-1a07576f-6f8e-4169-95e9-4bfed2fde750.png)
[latest.log](https://github.com/Talia-12/Hexal/files/10066530/latest.log)

**Comment by Talia-12** [comment]
Version 0.2.2 doesn't work with Hex Casting 0.10.1; I'm now releasing 0.2.3 to fix those issues.
