### ISSUE TITLE
[Suggestion] Link Media Balancing Toggle

### ISSUE THREAD

**Issue by FractalineHue** [Talia-12/Hexal#83]
Add a pattern that takes a link number and a boolean to toggle the media sharing of the link off/on.
Should work by both link entities must have it on to share media, toggling it on or off toggles both off if both share the same caster but both wisps have to seperately toggle it on if not same caster.
Should probably be disabled by default for different caster (so you can't just steal wisp media from someone) and enabled by default for same caster.
May also want a pattern that returns current state though that one might need to be a bit more complex? Since you can have Off, Self on other off, self off other on, and sharing (both on).

**Comment by Talia-12** [comment]
Implemented for the next version, didn't bother with any way of getting the current state of it
