### ISSUE TITLE
Entity Anchored Gate Creation fails due to range check on offset vector

### ISSUE THREAD

**Issue by ChaosAlpha** [Talia-12/Hexal#88]
Seems this check here should only be run in the Location Anchored Gate case? Currently, if I try to use (0,0,0) as offset for an Entity Anchored Gate while not near to world origin, the check fails and I cannot create the Gate.

https://github.com/Talia-12/Hexal/blob/de4ca64b9415363eb0144f1a8a9ed6cecde7721d/Common/src/main/java/ram/talia/hexal/common/casting/actions/spells/gates/OpMakeGate.kt#L34C30-L34C30

**Comment by Talia-12** [comment]
fixed for the next release
