### ISSUE TITLE
Duplication bug with Smelt and Mediafy

### ISSUE THREAD

**Issue by beholderface** [Talia-12/Hexal#89]
Hexal 0.2.16, Quilt 0.19.0-beta.13
You can duplicate items by copying an itemstack entity reference and then using Smelt or Mediafy Item on it multiple times in the same execution
Steps to reproduce:

1. Drop item on the ground
2. Raycast mantra, Scout's to get reference to it
3. Intro
4. Draw Mediafy Item (followed by Bookkeeper's V) or Smelt as many times as you want
5. Retro
6. Hermes
7. Morally-dubious profit

**Comment by Talia-12** [comment]
Fixed for next version
