### ISSUE TITLE
entityanchor is not visible

### ISSUE THREAD

**Issue by SamsTheNerd** [Talia-12/Hexal#90]
https://github.com/Talia-12/Hexal/blob/4fe6b76a7d2866b221709ef73aa7fda30aa7c5c2/Common/src/main/java/ram/talia/hexal/api/spell/iota/GateIota.java#L36C1-L36C1

the record is not visible to outside classes, should probably be public

Current workaround that might work is to just make an identical record and then unsafe cast to it.

**Comment by Talia-12** [comment]
fixed this for the next release
