### ISSUE TITLE
Documentation for Allow/Disallow Transfer Others is backwards

### ISSUE THREAD

**Issue by Robotgiggle** [Talia-12/Hexal#92]
In the online book, along with (presumably) the ingame one, the description text for the Allow Transfer Others spell is on the page for Disallow Transfer Others, and vice versa.
<img width="532" alt="image" src="https://github.com/Talia-12/Hexal/assets/88736742/7c06ec0e-aced-433b-babe-6fd12ffa1bbf">

**Comment by Talia-12** [comment]
fixed for the next release
