### ISSUE TITLE
Bound wisp consuming itself doesn't unbind it, and permanently locks you out of using Bind Wisp

### ISSUE THREAD

**Issue by Robotgiggle** [Talia-12/Hexal#93]
On the Hexxycraft server, I made a bound wisp self-destruct via casting Consume Wisp on itself, and I'm now unable to bind a new wisp. 

Initially, casting Familiar's Reflection returned an entity reference to the wisp, despite the fact that it seemingly no longer existed. Patterns like Compass Purification and Manager's Purification worked exactly as expected on this entity reference, ie returned the relevant information with no mishap.

In an attempt to properly unbind the wisp, I manually cast Consume Wisp on the entity reference returned by Familiar's Reflection. Doing so caused my casting grid to hang (ie the Hermes Gambit I used to trigger the effect turned grey), and when I closed and reopened the grid the Hermes I'd drawn was just gone. I drew it again, which seemed to work, resolving without mishap and turning all the remaining entity references to the wisp into NULL.

However, after doing this, I'm still unable to bind a new wisp - trying to do so fails silently, without even ending the overall cast if done partway through a hermes/wisp execution. Casting Familiar's Reflection mishaps, giving the following message in chat:
![image](https://github.com/Talia-12/Hexal/assets/88736742/8d4a87cf-e10f-432b-bcb3-65a3f3669dc1)

I appear to now be permanently locked out of using Bind Wisp. Is there anything I can do?

**Comment by Talia-12** [comment]
not going to close this till 0.2.17 has actually been tested on the server to confirm that it's fixed, but I *think* I fixed this properly

**Comment by Talia-12** [comment]
I think this is fixed now? reopen if not
