### ISSUE TITLE
The mote spells only use ints, when mote storage uses a long

### ISSUE THREAD

**Issue by beholderface** [Talia-12/Hexal#94]
Using Splitting Gambit with a number greater than (2^31)-1 mishaps, and running a Craft that would produce more than that number clamps the value. May well be other cases that I haven't seen.

(I think you already know about the Splitting Gambit one, but I don't know of any prior discussion of the Craft one, and there wasn't a github issue for this yet)

**Comment by beholderface** [comment]
Correction: I think I misinterpreted a wisp running out of media in the middle of a crafting hex (and leaving maxint of something in my nexus) as the output clamping issue in the original post
But the splitting gambit mishap is definitely a thing

**Comment by Talia-12** [comment]
alright, should be fixed for the next release; also fixed the possibility of OpCraftMote doing a long overflow
