### ISSUE TITLE
[Suggestion] Add a pattern which allows other players to use per-player patterns on a wisp

### ISSUE THREAD

**Issue by object-Object** [Talia-12/Hexal#96]
For example, Consume Wisp and Manager Purification would work on a "friendly wisp" without penalty.

Obviously the wisp being made friendly would need to cast this.

Naming suggestions:
* Friendly Gambit
* Become Friendly
* Extroversion (make friendly) and Introversion (make not friendly)

**Comment by Talia-12** [comment]
implemented for the next version
